// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDJXXIZmXmxcqIxKsfQAYD6qKN7uZTiyVc",
    authDomain: "templete-d9614.firebaseapp.com",
    projectId: "templete-d9614",
    storageBucket: "templete-d9614.appspot.com",
    messagingSenderId: "798180409726",
    appId: "1:798180409726:web:c888099e8c53a11168332f",
    measurementId: "G-K99MBGQPCL",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4lZa9R_E_9IdgWRlsP3E1gDCK0KLOTWI',
    appId: '1:798180409726:android:836222a623a5ad8968332f',
    messagingSenderId: '798180409726',
    projectId: 'templete-d9614',
    //storageBucket: 'antonx-flutter-template.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4lZa9R_E_9IdgWRlsP3E1gDCK0KLOTWI',
    appId: '1:798180409726:ios:58ea504346b8359e68332f',
    messagingSenderId: '798180409726',
    projectId: 'templete-d9614',
    // storageBucket: 'antonx-flutter-template.appspot.com',
    // iosClientId:
    //     '816831984722-rnmhv8pt2rrq4b3tpi1i6o72rddqo074.apps.googleusercontent.com',
    iosBundleId: 'com.futterTemplate',
  );
}
